version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.10.0
    commands:
      - echo "Installing dependencies..."
      - npm install
    build:
      commands:
        - echo "Building the application..."
        - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: dist
  discard-paths: no
